# Generated by Django 2.2.7 on 2019-11-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcategories',
            name='icon_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
