# Generated by Django 2.2.7 on 2019-11-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_popularcategories_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcategories',
            name='icon_class',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
